# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Code\python\pyqt\VideoMerge\view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(853, 597)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 731, 311))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 731, 31))
        self.label.setObjectName("label")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(750, 50, 91, 41))
        self.btn_add.setObjectName("btn_add")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(750, 100, 91, 41))
        self.btn_delete.setObjectName("btn_delete")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 410, 731, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 370, 731, 31))
        self.label_2.setObjectName("label_2")
        self.btn_select = QtWidgets.QPushButton(self.centralwidget)
        self.btn_select.setGeometry(QtCore.QRect(750, 410, 91, 41))
        self.btn_select.setObjectName("btn_select")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(10, 460, 831, 41))
        self.btn_start.setObjectName("btn_start")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 510, 831, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menu_2.setFont(font)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menu_3.setFont(font)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menu_4.setFont(font)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menu_5.setFont(font)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menu_6.setFont(font)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menu_7.setFont(font)
        self.menu_7.setObjectName("menu_7")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.actionNew.setFont(font)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.actionSaveAs.setFont(font)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionSaveAll = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.actionSaveAll.setFont(font)
        self.actionSaveAll.setObjectName("actionSaveAll")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.actionPrint.setFont(font)
        self.actionPrint.setObjectName("actionPrint")
        self.actionSaveImage = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.actionSaveImage.setFont(font)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.actionClose = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.actionClose.setFont(font)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionLeft = QtWidgets.QAction(MainWindow)
        self.actionLeft.setObjectName("actionLeft")
        self.actionCenter = QtWidgets.QAction(MainWindow)
        self.actionCenter.setObjectName("actionCenter")
        self.actionRight = QtWidgets.QAction(MainWindow)
        self.actionRight.setObjectName("actionRight")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionMiddle = QtWidgets.QAction(MainWindow)
        self.actionMiddle.setObjectName("actionMiddle")
        self.actionBottom = QtWidgets.QAction(MainWindow)
        self.actionBottom.setObjectName("actionBottom")
        self.actionStart_2 = QtWidgets.QAction(MainWindow)
        self.actionStart_2.setObjectName("actionStart_2")
        self.actionEnd = QtWidgets.QAction(MainWindow)
        self.actionEnd.setObjectName("actionEnd")
        self.actionWidgetBox = QtWidgets.QAction(MainWindow)
        self.actionWidgetBox.setObjectName("actionWidgetBox")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionNew)
        self.menu.addAction(self.actionOpen)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSaveAs)
        self.menu.addAction(self.actionSaveAll)
        self.menu.addSeparator()
        self.menu.addAction(self.actionPrint)
        self.menu.addAction(self.actionSaveImage)
        self.menu.addSeparator()
        self.menu.addAction(self.actionClose)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionUndo)
        self.menu_2.addAction(self.actionRedo)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionCut)
        self.menu_2.addAction(self.actionCopy)
        self.menu_2.addAction(self.actionPaste)
        self.menu_2.addAction(self.actionDelete)
        self.menu_2.addSeparator()
        self.menu_3.addAction(self.actionLeft)
        self.menu_3.addAction(self.actionCenter)
        self.menu_3.addAction(self.actionRight)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionStart)
        self.menu_3.addAction(self.actionMiddle)
        self.menu_3.addAction(self.actionBottom)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionStart_2)
        self.menu_3.addAction(self.actionEnd)
        self.menu_4.addAction(self.actionWidgetBox)
        self.menu_5.addAction(self.actionPreferences)
        self.menu_6.addAction(self.actionMinimize)
        self.menu_7.addAction(self.actionHelp)
        self.menu_7.addSeparator()
        self.menu_7.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VideoMerge 视频合并"))
        self.label.setText(_translate("MainWindow", "请添加需要合并的视频文件"))
        self.btn_add.setText(_translate("MainWindow", "添加"))
        self.btn_delete.setText(_translate("MainWindow", "删除"))
        self.label_2.setText(_translate("MainWindow", "请选择合成文件保存位置"))
        self.btn_select.setText(_translate("MainWindow", "选择"))
        self.btn_start.setText(_translate("MainWindow", "开始合成视频！"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "格式"))
        self.menu_4.setTitle(_translate("MainWindow", "视图"))
        self.menu_5.setTitle(_translate("MainWindow", "设置"))
        self.menu_6.setTitle(_translate("MainWindow", "窗口"))
        self.menu_7.setTitle(_translate("MainWindow", "帮助"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As"))
        self.actionSaveAll.setText(_translate("MainWindow", "Save All"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionSaveImage.setText(_translate("MainWindow", "Save Image"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionLeft.setText(_translate("MainWindow", "Left"))
        self.actionCenter.setText(_translate("MainWindow", "Center"))
        self.actionRight.setText(_translate("MainWindow", "Right"))
        self.actionStart.setText(_translate("MainWindow", "Top"))
        self.actionMiddle.setText(_translate("MainWindow", "Middle"))
        self.actionBottom.setText(_translate("MainWindow", "Bottom"))
        self.actionStart_2.setText(_translate("MainWindow", "Start"))
        self.actionEnd.setText(_translate("MainWindow", "End"))
        self.actionWidgetBox.setText(_translate("MainWindow", "Widget Box"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
